use std::fs;
use std::path::Path;

/// The wdio capability names a permission that only exists when the plugin is compiled
/// in; leaving the file in place would fail codegen for every ordinary build. So the
/// capability file is generated when `--features wdio` is on and deleted when it is not,
/// which keeps the default build — and therefore every release — free of it.
fn sync_wdio_capability() {
    let path = Path::new("capabilities/wdio.json");
    println!("cargo:rerun-if-changed=capabilities");
    if std::env::var_os("CARGO_FEATURE_WDIO").is_some() {
        let _ = fs::write(
            path,
            r#"{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "wdio",
  "description": "GUI end-to-end harness only. Generated by build.rs under --features wdio; never present in a release build.",
  "windows": ["main"],
  "permissions": ["wdio-webdriver:default"]
}
"#,
        );
    } else if path.exists() {
        let _ = fs::remove_file(path);
    }
}

fn main() {
    sync_wdio_capability();
    tauri_build::build()
}
