//! The `conduit` command's text, and putting it on disk.
//!
//! The shim is GENERATED, not bundled. Tauri's resource bundler does not reliably
//! preserve the executable bit, and Windows needs different content anyway; writing it
//! from Rust gives one code path that knows both the text and the mode. It keeps the
//! property bundling was for -- the installed app is what wrote it, so it cannot drift
//! from the app version -- and it matches how `hooks.rs` already generates its scripts.

use std::fs;
use std::path::{Path, PathBuf};

use serde::Serialize;

/// Present in every generated shim. `remove` refuses to delete a file without it, so it
/// can never destroy an unrelated `conduit` the user put on PATH themselves.
pub const SHIM_MARKER: &str = "conduit-cli-shim-v1";

pub fn shim_file_name() -> &'static str {
    if cfg!(windows) {
        "conduit.cmd"
    } else {
        "conduit"
    }
}

pub fn shim_text() -> String {
    if cfg!(windows) {
        shim_cmd()
    } else {
        shim_sh()
    }
}

pub fn shim_sh() -> String {
    format!(
        r##"#!/bin/sh
# {SHIM_MARKER} — generated by Conduit. Do not edit; reinstall from Settings.
set -eu

usage() {{ echo "usage: conduit <path> [--agent <id>]" >&2; exit 2; }}

target=""
agent=""
while [ $# -gt 0 ]; do
  case "$1" in
    -a|--agent) [ $# -ge 2 ] || usage; agent="$2"; shift 2 ;;
    -h|--help) usage ;;
    -*) echo "conduit: unknown option $1" >&2; usage ;;
    *) [ -z "$target" ] || usage; target="$1"; shift ;;
  esac
done
[ -n "$target" ] || target="."
[ -d "$target" ] || {{ echo "conduit: not a directory: $target" >&2; exit 1; }}
# Resolve symlinks so a checkout reached through a link is not added twice.
path=$(cd "$target" && pwd -P)

name="${{CONDUIT_DATA_DIR_NAME:-ConduitTauri}}"
case "$(uname -s)" in
  Darwin) base="$HOME/Library/Application Support" ;;
  *) base="${{XDG_DATA_HOME:-$HOME/.local/share}}" ;;
esac
dir="$base/$name"

esc=$(printf '%s' "$path" | sed 's/\\/\\\\/g; s/"/\\"/g')
if [ -n "$agent" ]; then
  body="{{\"path\":\"$esc\",\"agent\":\"$agent\"}}"
else
  body="{{\"path\":\"$esc\"}}"
fi

post() {{
  [ -f "$dir/hook-endpoint.sh" ] || return 1
  [ -f "$dir/cli-token" ] || return 1
  # One KEY=value line, sourced not executed — the contract hooks.rs writes it under.
  . "$dir/hook-endpoint.sh"
  [ -n "${{CONDUIT_HOOK_PORT:-}}" ] || return 1
  token=$(cat "$dir/cli-token")
  curl -sf -m 5 -X POST \
    -H "Content-Type: application/json" \
    -H "X-Conduit-Token: $token" \
    --data "$body" \
    "http://127.0.0.1:$CONDUIT_HOOK_PORT/open" >/dev/null 2>&1
}}

cold_start() {{
  if [ -n "${{CONDUIT_DATA_DIR_NAME:-}}" ]; then
    echo "conduit: no Conduit answering for CONDUIT_DATA_DIR_NAME=$CONDUIT_DATA_DIR_NAME." >&2
    echo "conduit: start it with 'CONDUIT_DATA_DIR_NAME=$CONDUIT_DATA_DIR_NAME pnpm tauri dev'." >&2
    exit 1
  fi
  case "$(uname -s)" in
    Darwin) open -b com.conduit.tauri >/dev/null 2>&1 || {{
              echo "conduit: could not launch Conduit." >&2; exit 1; }} ;;
    *) echo "conduit: Conduit is not running, and this platform has no bundle to launch." >&2
       exit 1 ;;
  esac
  n=0
  while [ $n -lt 30 ]; do
    # Re-read every attempt: the port is only published once the server binds.
    if post; then return 0; fi
    n=$((n + 1))
    sleep 0.5
  done
  echo "conduit: Conduit did not come up in time." >&2
  exit 1
}}

post || cold_start
"##
    )
}

pub fn shim_cmd() -> String {
    format!(
        r##"@echo off
rem {SHIM_MARKER} — generated by Conduit. Do not edit; reinstall from Settings.
setlocal enabledelayedexpansion

set "target="
set "agent="
:parse
if "%~1"=="" goto parsed
if /i "%~1"=="-a" (set "agent=%~2" & shift & shift & goto parse)
if /i "%~1"=="--agent" (set "agent=%~2" & shift & shift & goto parse)
set "target=%~1"
shift
goto parse
:parsed
if "%target%"=="" set "target=."
if not exist "%target%\" (echo conduit: not a directory: %target% 1>&2 & exit /b 1)
for %%I in ("%target%") do set "path_abs=%%~fI"

rem dirs::data_dir() is the ROAMING app data folder on Windows, not Local.
set "name=%CONDUIT_DATA_DIR_NAME%"
if "%name%"=="" set "name=ConduitTauri"
set "dir=%APPDATA%\%name%"

set "port="
if exist "%dir%\hook-endpoint.sh" (
  for /f "usebackq tokens=2 delims==" %%a in ("%dir%\hook-endpoint.sh") do set "port=%%a"
)
set "token="
if exist "%dir%\cli-token" (
  for /f "usebackq delims=" %%a in ("%dir%\cli-token") do set "token=%%a"
)

set "esc=!path_abs:\=\\!"
if "%agent%"=="" (
  set "body={{\"path\":\"!esc!\"}}"
) else (
  set "body={{\"path\":\"!esc!\",\"agent\":\"%agent%\"}}"
)

if not "!port!"=="" if not "!token!"=="" (
  curl.exe -sf -m 5 -X POST -H "Content-Type: application/json" ^
    -H "X-Conduit-Token: !token!" --data "!body!" ^
    "http://127.0.0.1:!port!/open" >nul 2>&1
  if not errorlevel 1 exit /b 0
)

if not "%CONDUIT_DATA_DIR_NAME%"=="" (
  echo conduit: no Conduit answering for CONDUIT_DATA_DIR_NAME=%CONDUIT_DATA_DIR_NAME%. 1>&2
  exit /b 1
)
echo conduit: Conduit is not running. Start it and try again. 1>&2
exit /b 1
"##
    )
}

#[derive(Debug, Clone, Serialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct ShimStatus {
    pub installed: bool,
    /// Absolute path of the installed shim, when installed.
    pub path: Option<String>,
    /// The directory it went into -- shown so the user can add it to PATH if needed.
    pub dir: Option<String>,
    /// Whether `dir` is already on this process's PATH.
    pub on_path: bool,
}

/// Only the Unix install ladder needs this — on Windows the target is always under
/// `%LOCALAPPDATA%`. Without the cfg it is dead code on the Windows leg, and clippy
/// there runs with `-D warnings`.
#[cfg(not(windows))]
fn dir_writable(dir: &Path) -> bool {
    if !dir.is_dir() {
        return false;
    }
    let probe = dir.join(".conduit-write-probe");
    match fs::File::create(&probe) {
        Ok(_) => {
            let _ = fs::remove_file(&probe);
            true
        }
        Err(_) => false,
    }
}

/// Where the shim goes. `/usr/local/bin` when it exists and is writable, else
/// `~/.local/bin`. `/usr/local/bin` does NOT exist on a clean macOS, and assuming it
/// does fails on exactly the machines least able to debug it.
pub fn install_dir() -> PathBuf {
    #[cfg(windows)]
    {
        let base = std::env::var("LOCALAPPDATA")
            .map(PathBuf::from)
            .unwrap_or_else(|_| dirs::data_local_dir().unwrap_or_else(std::env::temp_dir));
        base.join("Conduit").join("bin")
    }
    #[cfg(not(windows))]
    {
        let usr = PathBuf::from("/usr/local/bin");
        if dir_writable(&usr) {
            usr
        } else {
            dirs::home_dir()
                .unwrap_or_else(std::env::temp_dir)
                .join(".local")
                .join("bin")
        }
    }
}

fn dir_on_path(dir: &Path) -> bool {
    std::env::var_os("PATH")
        .map(|p| std::env::split_paths(&p).any(|e| e == dir))
        .unwrap_or(false)
}

pub fn status_in(dir: &Path) -> ShimStatus {
    let file = dir.join(shim_file_name());
    let ours = fs::read_to_string(&file)
        .map(|t| t.contains(SHIM_MARKER))
        .unwrap_or(false);
    ShimStatus {
        installed: ours,
        path: ours.then(|| file.to_string_lossy().into_owned()),
        dir: Some(dir.to_string_lossy().into_owned()),
        on_path: dir_on_path(dir),
    }
}

pub fn status() -> ShimStatus {
    status_in(&install_dir())
}

pub fn install_in(dir: &Path) -> Result<(), String> {
    fs::create_dir_all(dir).map_err(|e| format!("could not create {}: {e}", dir.display()))?;
    let file = dir.join(shim_file_name());
    // Refuse to clobber something we did not write -- same rule as remove.
    if let Ok(existing) = fs::read_to_string(&file) {
        if !existing.contains(SHIM_MARKER) {
            return Err(format!(
                "{} already exists and was not written by Conduit",
                file.display()
            ));
        }
    }
    fs::write(&file, shim_text())
        .map_err(|e| format!("could not write {}: {e}", file.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&file, fs::Permissions::from_mode(0o755))
            .map_err(|e| format!("could not make {} executable: {e}", file.display()))?;
    }
    Ok(())
}

pub fn remove_in(dir: &Path) -> Result<(), String> {
    let file = dir.join(shim_file_name());
    match fs::read_to_string(&file) {
        Ok(t) if t.contains(SHIM_MARKER) => {
            fs::remove_file(&file).map_err(|e| format!("could not remove {}: {e}", file.display()))
        }
        Ok(_) => Err(format!(
            "{} was not written by Conduit; leaving it alone",
            file.display()
        )),
        Err(_) => Ok(()),
    }
}

pub fn install() -> Result<ShimStatus, String> {
    let dir = install_dir();
    install_in(&dir)?;
    Ok(status_in(&dir))
}

pub fn remove() -> Result<ShimStatus, String> {
    let dir = install_dir();
    remove_in(&dir)?;
    Ok(status_in(&dir))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_shim_carries_the_marker_so_remove_never_deletes_a_strangers_binary() {
        assert!(shim_sh().contains(SHIM_MARKER));
        assert!(shim_cmd().contains(SHIM_MARKER));
    }

    #[test]
    fn sh_shim_resolves_the_data_dir_exactly_as_store_data_dir_does() {
        let s = shim_sh();
        assert!(s.contains("${CONDUIT_DATA_DIR_NAME:-ConduitTauri}"));
        assert!(
            s.contains("Library/Application Support"),
            "macOS base missing"
        );
        assert!(s.contains("XDG_DATA_HOME"), "Linux base missing");
    }

    #[test]
    fn cmd_shim_uses_appdata_because_dirs_data_dir_is_roaming_on_windows() {
        let s = shim_cmd();
        assert!(s.contains("%APPDATA%"));
        assert!(
            !s.contains("%LOCALAPPDATA%\\ConduitTauri"),
            "wrong roaming/local root"
        );
    }

    #[test]
    fn shims_read_the_published_port_and_the_token() {
        for s in [shim_sh(), shim_cmd()] {
            assert!(s.contains("hook-endpoint.sh"), "port discovery missing");
            assert!(s.contains("cli-token"), "token read missing");
            assert!(s.contains("X-Conduit-Token"), "token header missing");
            assert!(s.contains("/open"), "route missing");
        }
    }

    /// A dev build is started from a terminal by `pnpm tauri dev`; there is no bundle to
    /// launch. Cold-launching the INSTALLED app there is the state.json clobber
    /// CLAUDE.md warns about, so an explicit data dir must fail instead.
    #[test]
    fn sh_shim_refuses_to_cold_launch_when_a_dev_data_dir_is_named() {
        let s = shim_sh();
        let cold = s.split("cold_start()").nth(1).expect("cold_start missing");
        let guard = cold
            .find("CONDUIT_DATA_DIR_NAME")
            .expect("dev guard missing");
        let launch = cold.find("open -b").expect("bundle launch missing");
        assert!(
            guard < launch,
            "the dev guard must precede the bundle launch"
        );
    }

    #[test]
    fn sh_shim_escapes_the_path_into_json() {
        // A directory may legitimately contain a quote or a backslash.
        assert!(
            shim_sh().contains(r#"s/\\/\\\\/g"#),
            "backslash escape missing"
        );
    }

    #[test]
    fn shim_text_matches_the_platform() {
        #[cfg(windows)]
        {
            assert_eq!(shim_file_name(), "conduit.cmd");
            assert!(shim_text().contains("%APPDATA%"));
        }
        #[cfg(not(windows))]
        {
            assert_eq!(shim_file_name(), "conduit");
            assert!(shim_text().starts_with("#!/bin/sh"));
        }
    }

    fn tmp() -> PathBuf {
        let d = std::env::temp_dir().join(format!("conduit-shim-{}", uuid::Uuid::new_v4()));
        fs::create_dir_all(&d).unwrap();
        d
    }

    #[test]
    fn install_writes_the_shim_and_reports_it() {
        let dir = tmp();
        install_in(&dir).unwrap();
        let file = dir.join(shim_file_name());
        assert!(fs::read_to_string(&file).unwrap().contains(SHIM_MARKER));
        assert!(status_in(&dir).installed);
        fs::remove_dir_all(&dir).ok();
    }

    #[cfg(unix)]
    #[test]
    fn installed_shim_is_executable() {
        use std::os::unix::fs::PermissionsExt;
        let dir = tmp();
        install_in(&dir).unwrap();
        let mode = fs::metadata(dir.join(shim_file_name()))
            .unwrap()
            .permissions()
            .mode();
        assert_eq!(mode & 0o777, 0o755);
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn install_is_idempotent_and_rewrites_stale_text() {
        let dir = tmp();
        fs::write(
            dir.join(shim_file_name()),
            format!("#!/bin/sh\n# {SHIM_MARKER}\nexit 9\n"),
        )
        .unwrap();
        install_in(&dir).unwrap();
        assert!(fs::read_to_string(dir.join(shim_file_name()))
            .unwrap()
            .contains("/open"));
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn remove_deletes_our_shim() {
        let dir = tmp();
        install_in(&dir).unwrap();
        remove_in(&dir).unwrap();
        assert!(!status_in(&dir).installed);
        fs::remove_dir_all(&dir).ok();
    }

    /// The whole reason the marker exists.
    #[test]
    fn remove_refuses_a_file_we_did_not_write() {
        let dir = tmp();
        let file = dir.join(shim_file_name());
        fs::write(&file, "#!/bin/sh\necho someone elses conduit\n").unwrap();
        assert!(remove_in(&dir).is_err());
        assert!(file.exists(), "must not delete a stranger's binary");
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn status_reports_absent_cleanly() {
        let dir = tmp();
        let s = status_in(&dir);
        assert!(!s.installed);
        assert_eq!(s.path, None);
        fs::remove_dir_all(&dir).ok();
    }
}
